### ISSUE TITLE
Chrome Plugin -  Manual Transaction Naming

### ISSUE THREAD

**Issue by codethefurture123** [Cognizant-Digital-Engineering-PACE/CXOptimize#1]
Hi Team,

We are using the chrome plugin to capture client metrics. We wish to **manually feed in the transaction naming** to each page rather than using the page title or URL by default. Currently this feature is not working, can you please help us get this resolved.

Thanks,
Antony
antonynavin90@gmail.com
![cxo_chrome](https://user-images.githubusercontent.com/28569468/42841827-4f2977b8-89d9-11e8-8a9b-e20a2684d4e7.png)

**Comment by senthilkumarchinnasamycognizant** [comment]
Please tets latest plugin and let us know if the this can be closed
