### ISSUE TITLE
Need to exclude/filter few  monitoring requests

### ISSUE THREAD

**Issue by kowsalyacognizant** [Cognizant-Digital-Engineering-PACE/CXOptimize#5]
Hi,
In our applications, monitoring has been enabled, due to which monitoring requests (like Pushservlet in PEGA, Tealeaf in EXIZEN, dynatracemonitor) would get triggered automatically in certain intervals,
These requests sometime would have high response time so we would explicitly eliminate.

In CxOptimize, these monitoring requests are included in the HAR files that is causing deviation in the response time for transactions. 
For instances, the ‘xyz’ transaction is soft navigation, the ‘Backend time’ is 120120 ms (i.e: 120.12 secs). While checking in the HAR file, we found the Pushservlet [application monitoring] request took 2 mins was included in it. 

_Query:_
**Is there any option to exclude/Filter those requests in Cxoptimize?**

Regards
Kowsalya

**Comment by cognizantcxoptimize** [comment]
Option added to filter requests which are not required as part of collector logic and driven by properties
